apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: github-auth
  name: github-auth
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: github-auth
  template:
    metadata:
      labels:
        app: github-auth
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - image: public.ecr.aws/twisto/k8s-github-auth:latest
        name: k8s-git-auth
        env:
        - name: GIT_ORG
          value: gitOgranizationName
        ports:
        - containerPort: 3210
          hostPort: 3210
          protocol: TCP
          hostIP: 127.0.0.1
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
