---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-access-role
  namespace: testnamespace
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-team-binding
  namespace: testnamespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access-role
subjects:
- kind: Group
  name: gitUserTeamName
  apiGroup: rbac.authorization.k8s.io
